name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - master # o 'main' dependiendo de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        # Importante: El base-href debe coincidir con el nombre de tu repositorio
        run: flutter build web --release --base-href "/frontendGestion2026/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
